apiVersion: v1
kind: Service
metadata:
   name: server-service
   labels:
     app: server-service
      
spec:
   type: ClusterIP
   ports:
     - protocol: TCP
       port: 8000
       targetPort: 8000
   selector:
     app: server